### ISSUE TITLE
Can't add more admins or give privileges

### ISSUE THREAD

**Issue by Ph0non** [oddlama/vane#10]
For example, when I run `perm add Heiko admin`, I get the following long error message in the server console.

```
[14:36:20 INFO]: An unexpected error occurred. Please examine the console log and/or notify a server administator.
[14:36:20 WARN]: Unexpected exception while parsing console command "perm add Heiko admin"
org.bukkit.command.CommandException: Unhandled exception executing 'perm add Heiko admin' in org.oddlama.vane.core.command.Command$BukkitCommand(permission)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.5.jar:git-Paper-642]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-642]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Paper-642]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:453) ~[patched_1.16.5.jar:git-Paper-642]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.16.5.jar:git-Paper-642]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-642]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-642]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-642]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
        at org.oddlama.vane.core.command.Param.lambda$choose_any_player$3(Param.java:228) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:?]
        at org.oddlama.vane.core.command.Param.lambda$choose_any_player$e81bbdbc$2(Param.java:229) ~[?:?]
        at org.oddlama.vane.core.command.params.DynamicChoiceParam.parse(DynamicChoiceParam.java:51) ~[?:?]
        at org.oddlama.vane.core.command.params.DynamicChoiceParam.check_parse(DynamicChoiceParam.java:35) ~[?:?]
        at org.oddlama.vane.core.command.Param.check_accept(Param.java:317) ~[?:?]
        at org.oddlama.vane.core.command.Param.lambda$check_accept_delegate$6(Param.java:287) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
        at org.oddlama.vane.core.command.Param.check_accept_delegate(Param.java:288) ~[?:?]
        at org.oddlama.vane.core.command.Param.check_accept(Param.java:323) ~[?:?]
        at org.oddlama.vane.core.command.Param.lambda$check_accept_delegate$6(Param.java:287) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
        at org.oddlama.vane.core.command.Param.check_accept_delegate(Param.java:288) ~[?:?]
        at org.oddlama.vane.core.command.Param.check_accept(Param.java:323) ~[?:?]
        at org.oddlama.vane.core.command.Command$BukkitCommand.execute(Command.java:58) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-642]
        ... 8 more
```

Even the `/heads` command returns `unknown command` for all other players.

I run a [Docker Paper Server ](https://github.com/itzg/docker-minecraft-server)

**Comment by oddlama** [comment]
Thanks for the report, this is indeed a bug - although it is quite unlikely to get. The error basically hints that there is a (possibly offline) player registered on your server, for which your server knows the UUID but not the player's name.

I suspect you can work around the issue temporarily until I publish a fix, by finding out which player(s) is/are in this inconsistent state. All player related data should be saved in `world/playerdata`, if you know exactly who is currently playing on your server, you might be able to find some rouge entries that can be deleted.

If you make a backup of your playerdata you can also just do a binary search by deleting half of the playerdata and checking if the problem persists. If it persists, at least one bad entry is in the remaining files, if the problem is gone, all remaining files are fine. If you are unsure if it is a good idea to sift through playerdata I recommend just waiting until I upload the fix.

**Comment by oddlama** [comment]
Fixed
