### ISSUE TITLE
Possible NPE from unloaded world on portal selection:

### ISSUE THREAD

**Issue by ryantheleach** [oddlama/vane#142]
```
[vane-portals] Task #9 for vane-portals v1.6.7 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
    at org.oddlama.vane.portals.PortalDynmapLayerDelegate.update_marker(PortalDynmapLayerDelegate.java:111) ~[vane-portals-1.6.7.jar:?]
    at org.oddlama.vane.portals.PortalDynmapLayerDelegate.update_all_markers(PortalDynmapLayerDelegate.java:156) ~[vane-portals-1.6.7.jar:?]
    at org.oddlama.vane.portals.PortalDynmapLayerDelegate.create_or_load_layer(PortalDynmapLayerDelegate.java:88) ~[vane-portals-1.6.7.jar:?]
    at org.oddlama.vane.portals.PortalDynmapLayerDelegate.on_enable(PortalDynmapLayerDelegate.java:48) ~[vane-portals-1.6.7.jar:?]
    at org.oddlama.vane.portals.PortalDynmapLayer.delayed_on_enable(PortalDynmapLayer.java:50) ~[vane-portals-1.6.7.jar:?]
    at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-155]
    at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-155]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-155]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-155]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
    ```
    
    https://discord.com/channels/907277628816388106/907282692410863646/940917371177148426

I've deduced that the only real reason that this could be possible, is if a bukkit world containing a portal location is disabled.

Splitting portal storage into world based files and loading only the files of loaded worlds would fix this long term,

But maybe we should create an errored name at least, so people can hunt down / fix these portals before that happens?

Otherwise we could filter portal destinations out based on whether their worlds are loaded.

**Comment by oddlama** [comment]
Fixed. Portals are now filtered if worlds are not loaded and otherwise vane is now using world persistent data container to store portals, which means this szenario can only happen now when a world is unloaded while the server is running.
