### ISSUE TITLE
Vane-waterfall is not creating a paper-plugin.yml or plugin.yml

### ISSUE THREAD

**Issue by OwenKelly05** [oddlama/vane#195]
I'm trying to get my auto server start working but for some reason, the vane-waterfall plugin isn't creating the necessary files? I definitely feel like I'm doing something wrong and a lot of this is out of my league but here are the logs. I would appreciate if someone could assist me since the proxy guide is vague on the topic.

```
[02:05:49 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/vane-waterfall-1.11.0.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/vane-waterfall-1.11.0.jar' failed to load!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[paper-1.19.4.jar:git-Paper-545]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[paper-1.19.4.jar:git-Paper-545]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[paper-1.19.4.jar:git-Paper-545]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[paper-1.19.4.jar:git-Paper-545]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.19.4.jar:git-Paper-545]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[paper-1.19.4.jar:git-Paper-545]
	at net.minecraft.server.Main.main(Main.java:126) ~[paper-1.19.4.jar:git-Paper-545]
	at org.bukkit.craftbukkit.Main.main(Main.java:309) ~[paper-1.19.4.jar:git-Paper-545]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/vane-waterfall-1.11.0.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:54) ~[paper-1.19.4.jar:git-Paper-545]
	... 20 more
[02:05:51 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
```

**Comment by oddlama** [comment]
You are trying to load `vane-waterfall` with your PaperMC server. But it is not a plugin for PaperMC, but for a proxy software called [Waterfall](https://papermc.io/downloads/waterfall) which just happens to be by the people who made PaperMC.

The guide is a little vague on the basics, because it would be too much to reiterate on how to setup a proxy server. For most people this is not as easy as setting up a Minecraft server (as it involves more port stuff, inter process communication, etc.), so we require you to know what you are doing already. If you need help with the basics, I recommend asking on the [PaperMC Discord](https://discord.com/invite/papermc). If you have problems with vane-waterfall specifically, you can also ask in [our discord](https://discord.gg/RueJ6A59x2).

**Comment by OwenKelly05** [comment]
thanks for the quick response. will definitely look at the discord for support.
