### ISSUE TITLE
Pl3xmap Addon

### ISSUE THREAD

**Issue by knniDE** [oddlama/vane#197]
Does the Pl3xMap addon still work? If so, how do I install it? The official addons are listed as separate plugins and are installed that way. The one by Vane doesn't seem to be a standalone plugin. Thank you for your help <3

**Comment by oddlama** [comment]
The integration was a contribution. I would assume it still works, but I can't vouch for it. If I recall correctly, it's not a standalone plugin but something you have to put inside the plexmap folder, and which is loaded by plexmap itself.

**Comment by knniDE** [comment]
I can also recall that there used to be a separate "addons" folder. However, I believe that is no longer the case.
Could you please reach out to the contributor or something similar to see if they can fix the issue?

By the way, when using the latest version of Pl3xMap, I also receive the following error message from Vane Bedtime & Portals:

```[23:47:29 WARN]: [vane-bedtime] Task #12 for vane-bedtime v1.12.1 generated an exception
java.lang.NoClassDefFoundError: net/pl3x/map/event/Event
        at org.oddlama.vane.bedtime.BedtimePlexMapLayer.delayed_on_enable(BedtimePlexMapLayer.java:27) ~[vane-bedtime-1.12.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-45]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-45]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1112) ~[paper-1.20.1.jar:git-Paper-45]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-45]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.pl3x.map.event.Event
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 6 more
[23:47:29 WARN]: [vane-portals] Task #16 for vane-portals v1.12.1 generated an exception
java.lang.NoClassDefFoundError: net/pl3x/map/event/Event
        at org.oddlama.vane.portals.PortalPlexMapLayer.delayed_on_enable(PortalPlexMapLayer.java:27) ~[vane-portals-1.12.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-45]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-45]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1112) ~[paper-1.20.1.jar:git-Paper-45]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-45]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.pl3x.map.event.Event
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 6 more
```

**Comment by oddlama** [comment]
@Serial-ATA Are you still using Plexmap with vane and maybe have some insight on this?

**Comment by Serial-ATA** [comment]
Yeah so Pl3xMap completely removed the addon system in v3 back in April. It now expects standalone plugins.

I was working on converting the addon over to the new system a few weeks ago and never got around to finishing it. I'll look into finishing it in the next couple weeks. Hopefully they won't change its system again.

**Comment by oddlama** [comment]
I guess this could be beneficial for us in the long run, since now we can remove the plexmap addon completely and have the integration kick in if needed, like with dynmap or bluemap
