### ISSUE TITLE
/rg error

### ISSUE THREAD

**Issue by TOWUK** [oddlama/vane#218]
[02:35:17 INFO]: TOWUK issued server command: /rg
[02:35:17 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'rg' in org.oddlama.vane.core.command.Command$BukkitCommand(region)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-169]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-169]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2354) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2314) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-169]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Error while invoking functor org.oddlama.vane.regions.commands.Region::open_menu!
        at org.oddlama.vane.core.command.params.SentinelExecutorParam.execute(SentinelExecutorParam.java:129) ~[vane-core-1.12.3.jar:?]
        at org.oddlama.vane.core.command.check.ExecutorCheckResult.apply(ExecutorCheckResult.java:30) ~[vane-core-1.12.3.jar:?]
        at org.oddlama.vane.core.command.Command$BukkitCommand.execute(Command.java:58) ~[vane-core-1.12.3.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 22 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.oddlama.vane.regions.region.RegionGroup.owner()" because "group" is null
        at org.oddlama.vane.regions.Regions.may_administrate(Regions.java:643) ~[vane-regions-1.12.3.jar:?]
        at org.oddlama.vane.regions.menu.MainMenu.create(MainMenu.java:174) ~[vane-regions-1.12.3.jar:?]
        at org.oddlama.vane.regions.commands.Region.open_menu(Region.java:23) ~[vane-regions-1.12.3.jar:?]
        at org.oddlama.vane.core.functional.Consumer1.invoke(Consumer1.java:15) ~[vane-core-1.12.3.jar:?]
        at org.oddlama.vane.core.command.params.SentinelExecutorParam.execute(SentinelExecutorParam.java:124) ~[vane-core-1.12.3.jar:?]
        at org.oddlama.vane.core.command.check.ExecutorCheckResult.apply(ExecutorCheckResult.java:30) ~[vane-core-1.12.3.jar:?]
        at org.oddlama.vane.core.command.Command$BukkitCommand.execute(Command.java:58) ~[vane-core-1.12.3.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 22 more
> pl
[02:35:29 INFO]: Server Plugins (18):
[02:35:29 INFO]: Paper Plugins:
[02:35:29 INFO]:  - LibreLogin
[02:35:29 INFO]: Bukkit Plugins:
[02:35:29 INFO]:  - Essentials, EssentialsSpawn, floodgate, Geyser-Spigot, LuckPerms, Negativity, OldCombatMechanics, ProtocolLib, SkinsRestorer, vane-admin
[02:35:29 INFO]:  vane-bedtime, vane-core, vane-enchantments, vane-permissions, vane-portals, vane-regions, vane-trifles

![image](https://github.com/oddlama/vane/assets/28830162/0a815781-2e73-40e8-9890-ae1de6f32c21)

**Comment by TOWUK** [comment]
other ask:
region module needed another modules like a portal? why? i need just region module without modules

**Comment by Serial-ATA** [comment]
> other ask:
> region module needed another modules like a portal? why? i need just region module without modules

This shouldn't be the case anymore. #183 made it so you can use one without the other.
