### ISSUE TITLE
Update to 1.17 errors?

### ISSUE THREAD

**Issue by T-One** [oddlama/vane#22]
Hi,

i tried to update to PaperMC 1.17 and Vane 1.2.1 from 1.1.1 but it already stops at ProtocolLib.jar, i checked and got the newest one but it still isn't released for 1.17.

So Protocollib crashes with:

`22:44:09] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.17.0) has not yet been tested! Proceed with caution.
[22:44:11] [Server thread/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type={
    fields=[{modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.world.entity.EntityLiving}],
    methods=[{modifiers=[required: 0, banned: 0], params=[{Type: Exact class java.lang.String, Index: null}], paramCount=1}],
    constructors=[{modifiers=[required: 0, banned: 0], params=[{Type: class net.minecraft.server.dedicated.DedicatedServer instanceof input, Index: 0}, {Type: class net.minecraft.world.entity.EntityLiving instanceof input, Index: 2}], paramCount=3}]
`

Followed by all the vane plugins with:

`22:44:11] [Server thread/INFO]: [vane-core] Enabling vane-core v1.2.1
[22:44:11] [Server thread/ERROR]: Error occurred while enabling vane-core v1.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/ProtocolLibrary
        at org.oddlama.vane.core.module.Module.onEnable(Module.java:174) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:275) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.ProtocolLibrary
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.jar:git-Paper-"24880b9"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 10 more
[22:44:11] [Server thread/INFO]: [vane-core] Disabling vane-core v1.2.1
`

How do you got 1.17 running with you plugins?

**Comment by oddlama** [comment]
You need to use the latest version of protocollib, which has 1.17 support (get it here https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar)
