### ISSUE TITLE
Vane "Permission Denied" Error

### ISSUE THREAD

**Issue by Wingdingderp** [oddlama/vane#234]
I am currently making a 1.20.4 Paper Minecraft Server, and I am attempting to install Vane. I have installed ProtocolLib and I don't believe there are any conflicting plugins.

Here is the error for one of the Vane plugins:
`[19:27:26 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins/vane-permissions-1.14.0.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins/vane-permissions-1.14.0.jar' failed to load!
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[paper-1.20.4.jar:git-Paper-393]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[paper-1.20.4.jar:git-Paper-393]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[paper-1.20.4.jar:git-Paper-393]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[paper-1.20.4.jar:git-Paper-393]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.20.4.jar:git-Paper-393]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[paper-1.20.4.jar:git-Paper-393]
	at net.minecraft.server.Main.main(Main.java:131) ~[paper-1.20.4.jar:git-Paper-393]
	at org.bukkit.craftbukkit.Main.main(Main.java:325) ~[paper-1.20.4.jar:git-Paper-393]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.io.FileNotFoundException: plugins/vane-permissions-1.14.0.jar (Permission denied)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.open(Unknown Source) ~[?:?]
	at java.io.RandomAccessFile.<init>(Unknown Source) ~[?:?]
	at java.io.RandomAccessFile.<init>(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile$Source.get(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:?]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:?]
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:51) ~[paper-1.20.4.jar:git-Paper-393]

	... 20 more`

It does this for all of the Vane Plugins, such as, Core, Admin, Permissions, etc.

**Comment by oddlama** [comment]
Sounds like you copied the files with the root user (or at least another user than the user running the actual server), making them inaccessible to minecraft. Running `ls -la plugins/` should show that the permissions are not correct.

Depending on the exact problem, either give the files to the correct user with `chown` or adjust the mode with `chmod`.

**Comment by Wingdingderp** [comment]
So, what would be the command for this situation?

![image](https://github.com/oddlama/vane/assets/99741996/e2a14fad-3ba8-46ec-9093-96a25eb3d9ce)

**Comment by oddlama** [comment]
`chmod 644 plugins/*.jar` should suffice

**Comment by Wingdingderp** [comment]
That worked! Thanks for your help!
