### ISSUE TITLE
vane-enchantments  can not be loaded

### ISSUE THREAD

**Issue by Yearnu** [oddlama/vane#266]
```
[01:40:51 ERROR]: [BootstrapProviderStorage] Failed to run bootstrapper for plugins\vane-enchantments-1.15.0.jar. This plugin will not be loaded.
java.lang.NoClassDefFoundError: io/papermc/paper/registry/event/RegistryEvents
        at vane-enchantments-1.15.0.jar/org.oddlama.vane.enchantments.EnchantmentsBootstrapper.bootstrap(EnchantmentsBootstrapper.java:24) ~[vane-enchantments-1.15.0.jar:?]
        at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:36) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.storage.BootstrapProviderStorage$1.load(BootstrapProviderStorage.java:24) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:117) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enterBootstrappers(LaunchEntryPointHandler.java:26) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:66) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at net.minecraft.server.Main.main(Main.java:123) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.papermc.paper.registry.event.RegistryEvents
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 12 more
```

**Comment by oddlama** [comment]
Are you on minecraft version 1.21.1 as required by vane 1.15?

**Comment by oddlama** [comment]
> paper-1.20.6.jar

You must update your PaperMC
