### ISSUE TITLE
i have an issue with portal plugin

### ISSUE THREAD

**Issue by Ozmanse** [oddlama/vane#274]
[20:52:48 ERROR]: Error occurred while enabling vane-portals v1.15.0 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.oddlama.vane.portals.portal.PortalBlock.Type.ORİGİN
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at vane-portals-1.15.0.jar/org.oddlama.vane.portals.portal.PortalBlock$Type.valueOf(PortalBlock.java:70) ~[vane-portals-1.15.0.jar:?]
        at vane-portals-1.15.0.jar/org.oddlama.vane.portals.Portals.lambda$on_config_change$7(Portals.java:329) ~[vane-portals-1.15.0.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at vane-portals-1.15.0.jar/org.oddlama.vane.portals.Portals.lambda$on_config_change$8(Portals.java:328) ~[vane-portals-1.15.0.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at vane-portals-1.15.0.jar/org.oddlama.vane.portals.Portals.lambda$on_config_change$9(Portals.java:315) ~[vane-portals-1.15.0.jar:?]
        at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at vane-portals-1.15.0.jar/org.oddlama.vane.portals.Portals.on_config_change(Portals.java:308) ~[vane-portals-1.15.0.jar:?]
        at vane-core-1.15.0.jar/org.oddlama.vane.core.module.Module.config_change(Module.java:278) ~[vane-core-1.15.0.jar:?]
        at vane-core-1.15.0.jar/org.oddlama.vane.core.module.Module.reload_configuration(Module.java:393) ~[vane-core-1.15.0.jar:?]
        at vane-core-1.15.0.jar/org.oddlama.vane.core.module.Module.onEnable(Module.java:228) ~[vane-core-1.15.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]

**Comment by oddlama** [comment]
vane 1.15.0 is for minecraft 1.21.1, but the log suggests you are running 1.21. If that is the case, please try with an updated version.

**Comment by Ozmanse** [comment]
oh okey thx for the information

**Comment by oddlama** [comment]
Hmm not sure what's going on here, is there more context to the logs? Any previous failures?

**Comment by Ozmanse** [comment]
There is no previous failures. i am using these plugins with vane plugin 
![plugins](https://github.com/user-attachments/assets/2fc4a9b2-11fa-4aee-88ce-ef1f89f66abb)

**Comment by oddlama** [comment]
Did you edit the config? Your logs show `ORİGİN` written with two non-ASCII characters while it should be `ORIGIN`. So probably a typo in your config

**Comment by oddlama** [comment]
I suspect if you delete the config (to have it regenerated) and restart it will work again. Or you need to fix all typos

**Comment by Ozmanse** [comment]
> I suspect if you delete the config (to have it regenerated) and restart it will work again. Or you need to fix all typos

i already fix it. I changed my system language and it fixed itself. thanks <3
