### ISSUE TITLE
[vane-portals] Could not pass event InventoryClickEvent for 1.21.4

### ISSUE THREAD

**Issue by WaxenSs** [oddlama/vane#281]
I think this is normal since vane-portals 1.16 is not compatible with 1.21.4 but when I try to modify the portal style, I get an error message: 
```
Could not pass event InventoryClickEvent to vane-core v1.16.0 java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.displayName(net.kyori.adventure.text.Component)" because "meta" is null 
````

**Comment by oddlama** [comment]
Yeah this is to be expected in version updates. But I just uploaded a new release for 1.21.4 to github and modrinth (papermc hangar is down)

**Comment by WaxenSs** [comment]
Wow fast! Thanks again for this plugin.
The v17 update does not solve the problem, is this normal?
```
Could not pass event InventoryClickEvent to vane-core v1.16.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.displayName(net.kyori.adventure.text.Component)" because "meta" is null
        at vane-core-1.17.0.jar/org.oddlama.vane.util.ItemUtil.name_item(ItemUtil.java:107) ~[vane-core-1.17.0.jar:?]...
```

**Comment by sabsbremer** [comment]
To add to this, I've had the same error on current build paper 1.21.3 with v16 and it persists on v17
I've also tried regenerating the portals config but that doesn't seem to resolve the issue

`[14:34:13 ERROR]: Could not pass event InventoryClickEvent to vane-core v1.16.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.displayName(net.kyori.adventure.text.Component)" because "meta" is null
        at vane-core-1.17.0.jar/org.oddlama.vane.util.ItemUtil.name_item(ItemUtil.java:107) ~[vane-core-1.17.0.jar:?]
        at vane-core-1.17.0.jar/org.oddlama.vane.core.config.TranslatedItemStack.alternative(TranslatedItemStack.java:89) ~[vane-core-1.17.0.jar:?]
        at vane-portals-1.17.0.jar/org.oddlama.vane.portals.menu.StyleMenu$1.item(StyleMenu.java:544) ~[vane-portals-1.17.0.jar:?]
        at vane-core-1.17.0.jar/org.oddlama.vane.core.menu.MenuItem.<init>(MenuItem.java:38) ~[vane-core-1.17.0.jar:?]
        at vane-core-1.17.0.jar/org.oddlama.vane.core.menu.MenuItem.<init>(MenuItem.java:22) ~[vane-core-1.17.0.jar:?]
        at vane-portals-1.17.0.jar/org.oddlama.vane.portals.menu.StyleMenu$1.<init>(StyleMenu.java:537) ~[vane-portals-1.17.0.jar:?]
        at vane-portals-1.17.0.jar/org.oddlama.vane.portals.menu.StyleMenu.menu_item_block_selector(StyleMenu.java:476) ~[vane-portals-1.17.0.jar:?]
        at vane-portals-1.17.0.jar/org.oddlama.vane.portals.menu.StyleMenu.create(StyleMenu.java:286) ~[vane-portals-1.17.0.jar:?]
        at vane-portals-1.17.0.jar/org.oddlama.vane.portals.menu.SettingsMenu.lambda$menu_item_select_style$e7567bd1$1(SettingsMenu.java:223) ~[vane-portals-1.17.0.jar:?]
        at vane-core-1.17.0.jar/org.oddlama.vane.core.menu.MenuItem.lambda$new$11b12e99$1(MenuItem.java:26) ~[vane-core-1.17.0.jar:?]
        at vane-core-1.17.0.jar/org.oddlama.vane.core.menu.MenuItem.click(MenuItem.java:86) ~[vane-core-1.17.0.jar:?]
        at vane-core-1.17.0.jar/org.oddlama.vane.core.menu.Menu.click(Menu.java:173) ~[vane-core-1.17.0.jar:?]
        at vane-core-1.17.0.jar/org.oddlama.vane.core.menu.MenuManager.on_inventory_click(MenuManager.java:169) ~[vane-core-1.17.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor38.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3250) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1578) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1555) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1548) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:117) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1698) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1330) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by oddlama** [comment]
Oh sorry that was an oversight on my part. I explicitly tested the portal menu before uploading but missed that it happens only on the style submenu. Will update shortly.

**Comment by oddlama** [comment]
Alright please retry with 1.17.1 :)

**Comment by WaxenSs** [comment]
It's good thanks !
