### ISSUE TITLE
vance-core not found?

### ISSUE THREAD

**Issue by T-One** [oddlama/vane#3]
Hi, i used your 1.1.1 Release with all pugins and i get the following error:

`

11:28:54] [Server thread/ERROR]: Could not load 'plugins/vane-enchantments-1.1.1.jar' in folder 'plugins'
--
org.bukkit.plugin.UnknownDependencyException: Unknown dependency vane-core. Please download and install vane-core to run this plugin.
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.16.5.jar:git-Paper-585]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-585]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:251) ~[patched_1.16.5.jar:git-Paper-585]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-585]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-585]
at java.lang.Thread.run(Unknown Source) [?:?]

`

Vane-Core is in the plugins folder:

`drwxrwxr-x  3 199  199  uarch      10 Apr 18 11:28 ./
drwxrwxr-x  8 199  199  uarch      26 Apr 10 20:13 ../
drwxrwxr-x  2 199  199  uarch       3 Apr 10 21:30 bStats/
-rw-------  1 199  199  uarch   41835 Mar 22 19:38 vane-admin-1.1.1.jar
-rw-------  1 199  199  uarch   11184 Mar 22 19:38 vane-bedtime-1.1.1.jar
-rw-------  1 199  199  uarch 3194059 Mar 22 19:38 vane-core-1.1.1.jar
-rw-------  1 199  199  uarch   77413 Mar 22 19:38 vane-enchantments-1.1.1.jar
-rw-------  1 199  199  uarch  117196 Mar 22 19:38 vane-portals-1.1.1.jar
-rw-------  1 199  199  uarch   96892 Mar 22 19:38 vane-regions-1.1.1.jar
-rw-------  1 199  199  uarch   94466 Mar 22 19:38 vane-trifles-1.1.1.jar
`

Do i have to rename it to vane-core.jar?

**Comment by T-One** [comment]
I'm an idiot, protocollib missing...

**Comment by oddlama** [comment]
No worries, glad you figured it out. Have fun :)
