### ISSUE TITLE
Portals not starting anymore

### ISSUE THREAD

**Issue by Pumamori** [oddlama/vane#47]
```
07.09 22:33:06 [Server] ERROR Error occurred while enabling vane-portals v1.2.1 (Is it up to date?)
07.09 22:33:06 [Server] INFO org.oddlama.vane.external.json.JSONException: A JSONObject text must begin with '{' at 0 [character 1 line 1]
07.09 22:33:06 [Server] INFO at org.oddlama.vane.external.json.JSONTokener.syntaxError(JSONTokener.java:507) ~[vane-core-1.2.2.jar:?]
07.09 22:33:06 [Server] INFO at org.oddlama.vane.external.json.JSONObject.<init>(JSONObject.java:222) ~[vane-core-1.2.2.jar:?]
07.09 22:33:06 [Server] INFO at org.oddlama.vane.external.json.JSONObject.<init>(JSONObject.java:406) ~[vane-core-1.2.2.jar:?]
07.09 22:33:06 [Server] INFO at org.oddlama.vane.core.persistent.PersistentStorageManager.load(PersistentStorageManager.java:111) ~[vane-core-1.2.2.jar:?]
07.09 22:33:06 [Server] INFO at org.oddlama.vane.core.module.Module.load_persistent_storage(Module.java:346) ~[vane-core-1.2.2.jar:?]
07.09 22:33:06 [Server] INFO at org.oddlama.vane.core.module.Module.onEnable(Module.java:176) ~[vane-core-1.2.2.jar:?]
07.09 22:33:06 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-"6fa1983"]
07.09 22:33:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-"6fa1983"]
07.09 22:33:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-"6fa1983"]
07.09 22:33:06 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-"6fa1983"]
07.09 22:33:06 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-"6fa1983"]
07.09 22:33:06 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:277) ~[patched_1.17.1.jar:git-Paper-"6fa1983"]
07.09 22:33:06 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-"6fa1983"]
07.09 22:33:06 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-"6fa1983"]
07.09 22:33:06 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
```

At one point I also had an issue where I entered a portal and I came out in a completely different location but I'm assuming this is unrelated. Thank you!

**Comment by Pumamori** [comment]
It doesn't happen everytime and restart generally fixes it, but that shouldn't be necessary in the first place, right?

**Comment by oddlama** [comment]
Hmm thats indeed wierd, as your error message suggests a corrupt `storage.json` file, and therefore should persist over restarts. It is possible that vanilla minecraft teleported you somewhere near 0 0 0 when the plugin wasn't loaded. Did you experience any unclean system shutdowns, which could have caused the corruption?

**Comment by Pumamori** [comment]
Support said there was a DDOS attack at one point and server did freeze up once where I had to kill it - that might be why ;; That was the previous host though, this right here is new - I've deleted the entire config since I haven't changed any parameters and for now it's working again.

**Comment by oddlama** [comment]
Ah that's quite unlucky, and I'm glad it works again. Although the `storage.json` contains the locations of all actual portals and all persistent state similar to that, so my expectation was that you should see the error until you delete / fix that file.

Anyhow, there is a small timeframe where a server crash is critical, when these files are saved. I will make the saving more robust in the future so this doesn't happen again, even when the server crashes in that unfortunate timeframe.
