### ISSUE TITLE
Problems with enchantments, and client-side commands

### ISSUE THREAD

**Issue by patsore** [oddlama/vane#7]
So there are two problems.
The first one - client-side commands. After adding vane-permissions, most vanilla commands, such as /tp, /give, and many others, stopped to work. Thing is - i gave myself all the permissions, and I was opped too.
Second one is with vane-enchantments. I don't seem to be able to use /enchant with them, and sometimes see such an error -

> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:iron_file_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_seeding_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:netherite_reinforced_elytra_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:home_scroll_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_rake_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:unstable_scroll_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:golden_file_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:wooden_sickle_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:diamond_file_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:book_ancient_tome_of_knowledge_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_take_off_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_unbreakable_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:iron_sickle_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_angel_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:diamond_sickle_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_careless_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_wings_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_grappling_hook_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:wooden_file_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:stone_file_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:book_ancient_tome_of_the_gods_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:empty_xp_bottle_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:golden_sickle_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:stone_sickle_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_leafchopper_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_soulbound_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_hell_bent_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_angel_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_careless_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_seeding_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_wings_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_grappling_hook_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:netherite_reinforced_elytra_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:home_scroll_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_rake_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:unstable_scroll_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:empty_xp_bottle_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:book_ancient_tome_of_knowledge_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_leafchopper_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_soulbound_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_take_off_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_hell_bent_recipe removed now.
> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_enchantments:enchantment_unbreakable_recipe removed now.
The reason I posted both of these is because of the fact that the reason I installed vane-permissions was because I wanted to use vane enchantments.

**Comment by oddlama** [comment]
#### Regarding your first issue:

This behavior is intended. Vane chooses a quite radical approach here, as vane-permission removes all permissions that aren't explicitly granted. The reason for this is that many bukkit plugins are unfortunately written in sub-par quality, especially regarding security principles. More often than not a plugin author forgets to define sane defaults for their permissions. The same goes for bukkits default permissions. I want to give server owners full control over any permissions without any hidden defaults. So any permission that isn't explicitly set in the config, may safely be assumed as not given. This is also what makes vane-permissions quite unique. I understand that if you don't care about security, this can be considered annoying.

Also i want to emphasize, that there is absolutely no obligation to use vane-permissions. Although if you don't use it (see the installation guide) you will have to give player's the correct vane permissions by means of another permissions plugin or via bukkit permissions.

To list all permissions and their descriptions as registered to bukkit, you can execute `perm list permissions`. There you should find `minecraft.command.teleport`. Let say your user is added to the permission group `admin`. Execute `perm list permissions admin` to view the effective permissions for this group. If you have set `minecraft.command.teleport` in the config correctly, it will show up there, and `/tp` will work. I was able to test this successfully just now.

#### Regarding your second problem:

> [12:34:45 ERROR]: Tried to load unrecognized recipe: vane_trifles:iron_file_recipe removed now

Messages like these usually indicate that a plugin didn't load at all and the server discards the cached recipes. This should never be an actual problem. Not being able to use `/enchant` also indicates that either `vane-enchantments` isn't loaded, or another plugin registers a command with the same name (in this case try `/vane:enchant` instead). But I think it is more likely that there is a previous error in your log that you might have missed. Can you check which one it is and report back with the new information?

**Comment by patsore** [comment]
So sorry for the late answer.

> there is absolutely no obligation to use vane-permissions
I know, used it because it's easier with the custom vane permissions. Thanks for the elaborate answer on this topic.

Regarding the second issue -
I tried using /vane:enchantments:enchant (which, I presume, was what you meant by vane:enchant, as that command wasn't recognized), but the only argument it would accept was 'help', which is the reason why I don't think the problem was with it being loaded + there's a message during startup:

> [20:21:17 INFO]: [vane-core] Loading vane-core v1.1.2
>[20:21:17 INFO]: [vane-admin] Loading vane-admin v1.1.2
>[20:21:17 INFO]: [vane-portals] Loading vane-portals v1.1.2
>[20:21:17 INFO]: [vane-permissions] Loading vane-permissions v1.1.2
>[20:21:17 INFO]: [vane-enchantments] Loading vane-enchantments v1.1.2

so, again, problem is most likely, unrelated to loading.

I only have a few plugins installed. those are, as stated in /plugins: floodgate-bukkit, Geyser-Spigot, KeepChunks, ProtocolLib, vane-admin, vane-core, vane-enchantments, vane-permissions, vane-portals, vane-trifles, WorldEdit.
To my knowledge, none of these affect /enchant or enchantments.

running /debug start only gives messages similar to these
>[20:30:11 WARN]: Something's taking too long! 'root.tick.levels.ServerLevel[world] minecraft:overworld.tick.entities' took aprox 138.547586 ms
>[20:30:11 WARN]: Something's taking too long! 'root.tick.levels.ServerLevel[world] minecraft:overworld.tick' took aprox 143.569716 ms
>[20:30:11 WARN]: Something's taking too long! 'root.tick.levels.ServerLevel[world] minecraft:overworld' took aprox 143.626316 ms
>[20:30:11 WARN]: Something's taking too long! 'root.tick.levels' took aprox 146.982424 ms
>[20:30:11 WARN]: Something's taking too long! 'root.tick' took aprox 147.624915 ms
>[20:30:11 WARN]: Something's taking too long! 'root' took aprox 147.737102 ms


Ok so in the middle of this the issue resolved itself, after a plugin reinstall, so I can assume a broken file/download, but I'll still try to give as much info as I can on the issue.
I managed to reproduce the bug by running /reload
I don't know if you'll bother with this, since this command is advised not to be run, but nonetheless, here's the error:
>[20:33:44 ERROR]: Could not load 'plugins/vane-enchantments-1.1.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Cannot set already-set enchantment
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:141) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:947) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.Bukkit.reload(Bukkit.java:726) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:452) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-605]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot set already-set enchantment
	at org.bukkit.enchantments.Enchantment.registerEnchantment(Enchantment.java:345) ~[patched_1.16.5.jar:git-Paper-605]
	at org.oddlama.vane.enchantments.CustomEnchantment.<init>(CustomEnchantment.java:73) ~[?:?]
	at org.oddlama.vane.enchantments.enchantments.Angel.<init>(Angel.java:37) ~[?:?]
	at org.oddlama.vane.enchantments.Enchantments.<init>(Enchantments.java:44) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.16.5.jar:git-Paper-605]
	... 15 more
[20:33:44 ERROR]: Could not load 'plugins/vane-trifles-1.1.2.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency vane-enchantments. Please download and install vane-enchantments to run this plugin.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:947) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.Bukkit.reload(Bukkit.java:726) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-605]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:452) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-605]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-605]
	at java.lang.Thread.run(Thread.java:832) [?:?]

From what I see in the logs, it's a problem with reassigning enchantments, because it shows that they already exist, if you decide to investigate further - I'll be glad to provide any and all help, whether it be technical(though I only have the bare basics of java coding), or informational(system logs, server logs, packages installed...)

**Comment by oddlama** [comment]
> Regarding the second issue -
> I tried using /vane:enchantments:enchant (which, I presume, was what you meant by vane:enchant, as that command wasn't recognized), but the only argument it would accept was 'help', which is the reason why I don't think the problem was with it being loaded + there's a message during startup:

Yes sorry, that's what I meant.

> so, again, problem is most likely, unrelated to loading.

Yeah indeed seems like everything loades fine..

> I only have a few plugins installed. those are, as stated in /plugins: floodgate-bukkit, Geyser-Spigot, KeepChunks, ProtocolLib, vane-admin, vane-core, vane-enchantments, vane-permissions, vane-portals, vane-trifles, WorldEdit.
> To my knowledge, none of these affect /enchant or enchantments.
> 
> running /debug start only gives messages similar to these
> 
> > [20:30:11 WARN]: Something's taking too long! 'root.tick.levels.ServerLevel[world] minecraft:overworld.tick.entities' took aprox 138.547586 ms
> > [20:30:11 WARN]: Something's taking too long! 'root.tick.levels.ServerLevel[world] minecraft:overworld.tick' took aprox 143.569716 ms
> > [20:30:11 WARN]: Something's taking too long! 'root.tick.levels.ServerLevel[world] minecraft:overworld' took aprox 143.626316 ms
> > [20:30:11 WARN]: Something's taking too long! 'root.tick.levels' took aprox 146.982424 ms
> > [20:30:11 WARN]: Something's taking too long! 'root.tick' took aprox 147.624915 ms
> > [20:30:11 WARN]: Something's taking too long! 'root' took aprox 147.737102 ms

Hmm this is all unrelated to any plugins and only PaperMC server code. So nothing unusual.

> Ok so in the middle of this the issue resolved itself, after a plugin reinstall, so I can assume a broken file/download, but I'll still try to give as much info as I can on the issue.
> I managed to reproduce the bug by running /reload

Interesting, in that case I guess the plugin wasn't loaded by the server because the file was corrupt, although it seems unlikely if it's something that occurs randomly..

> I don't know if you'll bother with this, since this command is advised not to be run, but nonetheless, here's the error:
> [...]
> From what I see in the logs, it's a problem with reassigning enchantments, because it shows that they already exist, if you decide to investigate further - I'll be glad to provide any and all help, whether it be technical, or informational(system logs, server logs, packages installed...)

Thanks, this is actually a quite good indicator of what happens. The plugin is reloaded, but fails and gets disabled by the server as a consequence. Unfortunately, the reason it fails is tied to the problem that bukkit doesn't actually support registering new enchantments. They have to be registered before the world loads, which means before plugins are enabled. But reloading will reloads the whole jar file, which will in any case cause enchantments to be registered too late. Consequently, we cannot support `/reload` properly, because the minecraft server doesn't support it. This unfortunately means that until minecraft (and bukkit) support this feature, which may be never, `/reload` will cause issues for vane-enchantments. But the rest of the plugins should be reloadable. :/

Anyway, I hope the issue has actually solved itself for you. If it hasn't, feel free to reopen this issue.
