### ISSUE TITLE
vane-trifles depends on vane-enchantments

### ISSUE THREAD

**Issue by ryantheleach** [oddlama/vane#89]
vane-trifles will not load without vane-enchantments, 

It kinda defeats the purpose of separating the plugins, if trifles has a hard dependency on enchantments.

```
[13:48:46 ERROR]: Could not load 'plugins/vane-trifles-1.6.7.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [vane-enchantments]. Please download and install these plugins to run 'vane-trifles'.
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:290) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:421) ~[paper-1.18.1.jar:git-Paper-77]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:285) ~[paper-1.18.1.jar:git-Paper-77]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-77]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-77]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by oddlama** [comment]
Definitely not ideal, but required at the moment. You can still disable vane-enchantments in its entirety in the config if you need it for the dependency.

**Comment by oddlama** [comment]
Whoops I kind of duplicated this. Tracked by #132 now.
